# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "Louie" = super.buildPythonPackage rec {
    pname = "Louie";
    version = "2.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/f2/f8/f9dfd97003f1c120dca1ed4dc9e3e16b74b583ce5bcb2d9b013142b6bee2/Louie-2.0.tar.gz";
      sha256 = "0na3lqpbh2yyns1ww0s6pvzas4xsn1snv9j7asr7acd8sa4g1h82";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    checkInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
  };
}
