from enum import Enum

BROADCAST_IP = "192.168.0.255"
BROADCAST_PORT = 5973
CLIENT_BASE_PORT = 5980  # TODO: adjust as needed
IDENT_SERVER = "IDServer"
IDENT_CLIENT = "IDClient"
SHUTDOWN_SERVER = "ShutdownServer"
UPDATE_GROUP_VIEW = "UpdateGV"
ELECTION_MESSAGE = "ElectionMessage"
MAX_TRIES = 3
BUFFER_SIZE = 1024
MAX_MSG_BUFF_SIZE = 50

class State(Enum):
    PENDING = 0
    LEADER = 1
    MEMBER = 2
